spring:


  application:
    name: Tregusto
  server:
    port: 8082

  liquibase:
    enabled: ${LIQUIBASE_ENABLED:true}
    change-log: ${LIQUIBASE_CHANGELOG:classpath:db/changelog/db.changelog-master.xml}


  datasource:
    url: ${POSTGRESQL_URL}
    username: ${POSTGRESQL_USER}
    password: ${POSTGRESQL_PASS}


  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  logging:
    level:
      org.springframework.security: DEBUG


##################################################
# Application Configuration
##################################################
application:
#  config:
#    name: "Tregusto"
#    public-url: "http://tregusto.dev.gopartner.fr"
#    otp-expiration-minutes: 10
  ##################################################
  # CORS Configuration
  ##################################################
  authentication:
    api-allowed-origins: ${CORS_ALLOWED_ORIGINS}

