openapi: 3.0.2
info:
  title: Account API
  version: 1.0.0
  description: Account endpoints and schemas for Tregusto
servers:
  -
    url: 'http://localhost:8080/api/v1/account'
    description: Development server
paths:
  /accounts/me:
    get:
      tags:
        - account
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Account'
          description: Successfully retrieved current Account
        '401':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Unauthorized - User not authenticated
        '500':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Internal server error
      security:
        -
          localAuthServer: []
        -
          bearerAuth: []
      operationId: getCurrentAccount
      summary: Get the Account for current authenticated user
      description: Returns information about the Account the currently authenticated user
  /user/verification/confirm:
    post:
      tags:
        - Account
      parameters:
        -
          name: email
          description: ''
          schema:
            type: string
          in: query
          required: true
        -
          name: otp
          description: ''
          schema:
            type: string
          in: query
          required: true
      responses:
        '201':
          description: Successfully activated Account.
        '401':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Unauthorized - User not authenticated
        '500':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Internal server error
      operationId: activateUserAccount
      summary: Activate User account.
  /users:
    post:
      requestBody:
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/UserAccountProfile'
        required: true
      tags:
        - Account
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserAccount'
          description: Successfully created new Owner Account.
        '401':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Unauthorized - User not authenticated
        '500':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Internal server error
      operationId: createNewUserAccount
      summary: Create new User account.
  /user/verification/resend:
    post:
      tags:
        - Account
      parameters:
        -
          name: email
          description: ''
          schema:
            type: string
          in: query
          required: true
      responses:
        '201':
          description: Successfully resent verification code Account.
        '400':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CustomError'
          description: Bad request - resending otp code.
        '401':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Unauthorized - User not authenticated
        '500':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Internal server error
      operationId: verifyUserAccount
      summary: Resent verification code.
components:
  schemas:
    Account:
      required:
        - id
        - email
      type: object
      properties:
        id:
          format: int64
          description: Unique identifier of the user
          type: integer
          example: 123e4567-e89b-12d3-a456-426614174000
        name:
          description: Full name of the user
          type: string
          example: John Doe
        firstName:
          description: First name of the user
          type: string
          example: John
        lastName:
          description: Last name of the user
          type: string
          example: Doe
        email:
          format: email
          description: Email address of the user
          type: string
          example: john.doe@example.com
    Error:
      type: object
      properties:
        code:
          description: Error code
          type: string
        message:
          description: Error message
          type: string
        details:
          description: Additional details about the error
          type: array
          items:
            type: object
            properties:
              description:
                description: Detailed description of the error
                type: string
        timestamp:
          format: date-time
          description: Timestamp of the error
          type: string
    CustomError:
      description: ''
      required:
        - message
        - status
        - code
        - timestamp
      type: object
      properties:
        message:
          description: ''
          type: string
        status:
          description: ''
          type: string
        code:
          description: ''
          type: integer
        timestamp:
          format: date-time
          description: ''
          type: string
    UserAccount:
      description: ''
      required:
        - lastName
        - firstName
        - idCardNumber
        - address
        - phoneNumber
        - email
        - accountStatus
        - postalCodeId
        - password
        - role
      type: object
      properties:
        id:
          format: int64
          description: '                    '
          type: integer
        externalUserId:
          description: ''
          type: string
        lastName:
          description: ''
          type: string
        firstName:
          description: ''
          type: string
        idCardNumber:
          description: ''
          type: string
        address:
          description: ''
          type: string
        phoneNumber:
          description: ''
          type: string
        email:
          description: ''
          type: string
        postalCodeId:
          format: int64
          description: ''
          type: integer
        password:
          description: ''
          type: string
        role:
          description: ''
          enum:
            - OWNER
            - TENANT
            - DRIVER
            - SUPER_ADMIN
          type: string
        accountStatus:
          description: ''
          enum:
            - ACTIVE
            - PENDING
            - CONTRACT_SIGNED
          type: string
    UserAccountProfile:
      description: ''
      required:
        - lastName
        - firstName
        - idCardNumber
        - address
        - phoneNumber
        - email
        - accountStatus
        - postalCodeId
        - password
        - role
      type: object
      properties:
        id:
          format: int64
          description: '                    '
          type: integer
        externalUserId:
          description: ''
          type: string
        lastName:
          description: ''
          type: string
        firstName:
          description: ''
          type: string
        idCardNumber:
          description: ''
          type: string
        address:
          description: ''
          type: string
        phoneNumber:
          description: ''
          type: string
        email:
          description: ''
          type: string
        postalCodeId:
          format: int64
          description: ''
          type: integer
        password:
          description: ''
          type: string
        idCardFront:
          format: binary
          description: ''
          type: string
        idCardBack:
          format: binary
          description: ''
          type: string
        role:
          description: ''
          enum:
            - OWNER
            - TENANT
            - DRIVER
            - SUPER_ADMIN
          type: string
        accountStatus:
          description: ''
          enum:
            - ACTIVE
            - PENDING
            - CONTRACT_SIGNED
          type: string
  securitySchemes:
    bearerAuth:
      scheme: bearer
      bearerFormat: JWT
      type: http
      description: JWT Bearer token authentication
    localAuthServer:
      flows:
        authorizationCode:
          authorizationUrl: 'http://localhost:9090/realms/Tregusto/protocol/openid-connect/auth'
          tokenUrl: 'http://localhost:9090/realms/Tregusto/protocol/openid-connect/token'
          scopes:
            openid: OpenID Connect scope
      type: oauth2
      description: Keycloak OpenID Connect authentication
tags:
  -
    name: Tregusto
    description: ''
