openapi: 3.0.2
info:
  title: Test
  version: 1.0.0
paths:
  /test:
    get:
      tags:
        - Authentication
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApplicationStatus'
                properties:
                  message:
                    type: string
                    example: Spring boot is working!
          description: Returns 200 status code with status message
      operationId: getAppStatus
      summary: test if spring boot application is healthy
components:
  schemas:
    ApplicationStatus:
      description: ''
      required:
        - status
      type: object
      properties:
        status:
          description: ''
          type: string
tags:
  -
    name: TREGUSTO
    description: ''
